### ISSUE TITLE
Style visited links for docs content differently

### ISSUE THREAD

**Issue by NV** [montagejs/montagejs.org#31]
Can we style visited content links somewhat differently from unvisited ones? They could be purple-ish or just less bright. Something like:

``` css
.content a:visited {
    color: hsl(220, 70%, 70%);
}
```
